version: "3.5"

networks:
  myeth-network:
    name: myeth-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  root_ethdb:
    build:
      context: ./go-ethereum
    image: myeth
    container_name: root_ethdb
    restart: always
    volumes:
      - ./root-node-config:/etc/config
      - ./node-data/root-node:/home/data
    ports:
      - 30303:30303
    command: sh -c "geth --datadir /home/data --networkid 9079 --nodiscover"
    networks:
      myeth-network:
        ipv4_address: 172.28.0.10
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2000M

  node1_ethdb:
    image: myeth
    container_name: node1_ethdb
    restart: always
    volumes:
      - ./root-node-config:/etc/config
      - ./node-data/node1:/home/data
    command: sh -c "geth --datadir /home/data --networkid 9079 --nodiscover --rpc --rpcapi eth,net,web3,personal --rpcaddr "0.0.0.0" --rpcport 8545"
    ports:
      - 30304:30303
      - 8545:8545
    networks:
      myeth-network:
        ipv4_address: 172.28.0.11
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2000M

  # node2_ethdb:
  #   image: myeth
  #   container_name: node2_ethdb
  #   restart: always
  #   volumes:
  #     - ./root-node-config:/etc/config
  #     - ./node-data/node2:/home/data
  #   command: sh -c "geth --datadir /home/data --networkid 9079 --nodiscover"
  #   ports:
  #     - 30305:30303
  #   networks:
  #     myeth-network:
  #       ipv4_address: 172.28.0.12
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "1"
  #         memory: 1000M
